In [144]:
import pandas as pd
import numpy as np
import cassiopeia as cas

In [4]:
# scGESTALT(2018) Zebrafish brain
# Gene Expression Omnibus Accesion: Series GSE105010 Sample GSM2813986
df = pd.read_csv("GSM2813986_ZF3.GestMaster.txt", sep='\t')
df

,Unnamed: 0,CellNum,CellBarcode,CellUMI,BarcodeKey,ClusterIdent,HMID,Readname
0,1,1,F6-DEW142_AAACACGG-TAAGACGG,TATTCTTGTG,DEW142_bcAAVQ,8,59D+141-59D+141-59D+141-99D+208-99D+208-99D+20...,NS500488:132:H7JCTAFXX:1:11101:8025:576_TATTCT...
1,2,2,F6-DEW142_AAACCGCC-GCAAAGCC,CACTCCTGGC,DEW142_bcACDD,41,25I+140+GAAAGCTAGCGCCCTCGCCCTCGAT-NONE-NONE-9D...,NS500488:132:H7JCTAFXX:1:11101:8025:16_CACTCCT...
2,3,3,F6-DEW142_AAACGTGA-CCCATCTG,AAAGTTACCT,DEW142_bcADBS,13,NONE-3I+163+CCC&53D+167-53D+167-53D+167-349D+2...,NS500488:132:H7JCTAFXX:1:11101:8025:66_AAAGTTA...
3,4,5,F6-DEW142_AAAGCCCG-ACTCACCG,CTAGTGTTAA,DEW142_bcAFZD,25,1549D+127-1549D+127-1549D+127-1549D+127-1549D+...,NS500488:132:H7JCTAFXX:1:11101:8025:156_CTAGTG...
4,5,6,F6-DEW142_AACAGAAC-CTTCGCAC,TTCTGCCTTC,DEW142_bcAIZR,29,10D+131-NONE-NONE-NONE-374D+224-374D+224-374D+...,NS500488:132:H7JCTAFXX:1:11101:8025:657_TTCTGC...
...,...,...,...,...,...,...,...,...
371,372,793,F6-DEW148_TAGGTACG-ACTGAGTT,GAGACTGTGA,DEW148_bcHKAV,2,140D+141-140D+141-140D+141-140D+141-140D+141-1...,NS500488:132:H7JCTAFXX:1:11101:8025:384_GAGACT...
372,373,795,F6-DEW148_TCGTGGGT-AGTGAAAG,GTCAGCTTTT,DEW148_bcHWVT,7,NONE-3I+163+CCC&53D+167-53D+167-53D+167-133D+2...,NS500488:132:H7JCTAFXX:1:11101:8025:189_GTCAGC...
373,374,797,F6-DEW148_TGAATCCT-GTTCAACT,CAAAGCAGGA,DEW148_bcIAQM,17,NONE-3I+163+CCC&1I+167+T-NONE-9D+217-1I+248+G-...,NS500488:132:H7JCTAFXX:1:11101:8025:175_CAAAGC...
374,375,799,F6-DEW148_TGGGAATT-GCTTTGGC,AAGTCCAATG,DEW148_bcIIGE,0,140D+141-140D+141-140D+141-140D+141-140D+141-1...,NS500488:132:H7JCTAFXX:1:11101:8025:97_AAGTCCA...
375,376,800,F6-DEW148_TGTTATCA-CCCGACTT,TGATTACCAG,DEW148_bcIJPX,2,140D+141-140D+141-140D+141-140D+141-140D+141-1...,NS500488:132:H7JCTAFXX:1:11101:8025:165_TGATTA...

In [155]:
allele_table_rows = []

for index, row in df.iterrows():

    #Split indel info into 10 sites
    sites = row['HMID'].split('-')

    allele_table_rows.append({
        'cellBC': row['CellBarcode'],
        'intBC': 'ZF3',
        'allele': row['HMID'].replace('-', ''),
        'r1': sites[0],
        'r2': sites[1], 
        'r3': sites[3],
        'r4': sites[4], 
        'r5': sites[5],
        'r6': sites[6], 
        'r7': sites[7],
        'r8': sites[8], 
        'r9': sites[7],
        'r10': sites[9], 
        'UMI': row['Readname'].split('_')[2],
        'sampleID': 'ZF3'
        })

allele_table = pd.DataFrame(allele_table_rows)
allele_table.head(5)

,cellBC,intBC,allele,r1,r2,r3,r4,r5,r6,r7,r8,r9,r10,UMI,sampleID
0,F6-DEW142_AAACACGG-TAAGACGG,ZF3,59D+14159D+14159D+14199D+20899D+20899D+20899D+...,59D+141,59D+141,99D+208,99D+208,99D+208,99D+208,NONE,1I+356+C,NONE,NONE,39,ZF3
1,F6-DEW142_AAACCGCC-GCAAAGCC,ZF3,25I+140+GAAAGCTAGCGCCCTCGCCCTCGATNONENONE9D+21...,25I+140+GAAAGCTAGCGCCCTCGCCCTCGAT,NONE,9D+217,12D+244,NONE,NONE,NONE,NONE,NONE,NONE,38,ZF3
2,F6-DEW142_AAACGTGA-CCCATCTG,ZF3,NONE3I+163+CCC&53D+16753D+16753D+167349D+23734...,NONE,3I+163+CCC&53D+167,53D+167,349D+237,349D+237,349D+237,349D+237,349D+237,349D+237,349D+237,39,ZF3
3,F6-DEW142_AAAGCCCG-ACTCACCG,ZF3,1549D+1271549D+1271549D+1271549D+1271549D+1271...,1549D+127,1549D+127,1549D+127,1549D+127,1549D+127,1549D+127,1549D+127,1549D+127,1549D+127,1549D+127,39,ZF3
4,F6-DEW142_AACAGAAC-CTTCGCAC,ZF3,10D+131NONENONENONE374D+224374D+224374D+224374...,10D+131,NONE,NONE,374D+224,374D+224,374D+224,374D+224,374D+224,374D+224,374D+224,39,ZF3

In [156]:
indel_priors = cas.pp.compute_empirical_indel_priors(allele_table, grouping_variables=['cellBC'])
indel_priors.sort_values(by='count', ascending=False).head(5)

                                   count      freq
indel
9D+217                             133.0  0.353723
25I+140+GAAAGCTAGCGCCCTCGCCCTCGAT  107.0  0.284574
140D+141                            83.0  0.220745
54D+301                             56.0  0.148936
OUT                                 32.0  0.085106

In [157]:
character_matrix, priors, state_2_indel = cas.pp.convert_alleletable_to_character_matrix(allele_table,
                                                                                         allele_rep_thresh = 0.5,
                                                                                         mutation_priors = indel_priors)
character_matrix.head()

Dropping the following intBCs due to lack of diversity with threshold 0.5: ['ZF3r10']

Processing characters:   0%|          | 0/9 [00:00<?, ?it/s]

                             r1  r2  r3  r4  r5  r6  r7  r8  r9
F6-DEW142_AAACACGG-TAAGACGG   1   1   1   1   1   1   0   1   0
F6-DEW142_AAACCGCC-GCAAAGCC   2   0   2   2   0   0   0   0   0
F6-DEW142_AAACGTGA-CCCATCTG   0   2   3   3   2   2   1   2   1
F6-DEW142_AAAGCCCG-ACTCACCG   3   3   4   4   3   3   2   3   2
F6-DEW142_AACAGAAC-CTTCGCAC   4   0   0   5   4   4   3   4   3

In [159]:
cas_tree = cas.data.CassiopeiaTree(character_matrix=character_matrix, priors=priors)

cell_meta = allele_table.groupby('cellBC').agg({"intBC": 'nunique', 'UMI': 'sum', 'sampleID': 'unique'})
cell_meta['sampleID'] = [x[0] for x in cell_meta['sampleID']]

missing_proportion = (character_matrix == -1).sum(axis=0) / character_matrix.shape[0]
uncut_proportion = (character_matrix == 0).sum(axis=0) / character_matrix.shape[0]
n_unique_states = character_matrix.apply(lambda x: len(np.unique(x[(x != 0) & (x != -1)])), axis=0)

character_meta = pd.DataFrame([missing_proportion, uncut_proportion, n_unique_states], index = ['missing_prop', 'uncut_prop', 'n_unique_states']).T

cas_tree.cell_meta = cell_meta
cas_tree.character_meta = character_meta

In [160]:
# Use the standard VanillaGreedySolver
vanilla_greedy = cas.solver.VanillaGreedySolver()
vanilla_greedy.solve(cas_tree, collapse_mutationless_edges=True)

In [161]:
with open("ZF3_greedy_tree.nwk", "w") as f:
    f.write(cas_tree.get_newick())